#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# Hermes Dashboard — Universal Installer
# Works on Linux (x86_64/aarch64) and macOS (Intel/Apple Silicon)
# ═══════════════════════════════════════════════════════════════════
set -euo pipefail

DASHBOARD_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKEND_DIR="$DASHBOARD_DIR/backend"
PYTHON=""

# ── Colors ──────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

info()  { echo -e "${CYAN}▸${NC} $*"; }
ok()    { echo -e "${GREEN}✓${NC} $*"; }
warn()  { echo -e "${YELLOW}⚠${NC} $*"; }
err()   { echo -e "${RED}✗${NC} $*" >&2; }
banner(){ echo -e "\n${BOLD}${CYAN}$*${NC}\n"; }

# ── Detect OS ───────────────────────────────────────────────────────
detect_os() {
    case "$(uname -s)" in
        Linux*)  OS="linux";;
        Darwin*) OS="macos";;
        *)       err "Unsupported OS: $(uname -s)"; exit 1;;
    esac
    ARCH="$(uname -m)"
    ok "Detected: $OS ($ARCH)"
}

# ── Find Python ─────────────────────────────────────────────────────
find_python() {
    for candidate in python3.12 python3.11 python3; do
        if command -v "$candidate" &>/dev/null; then
            local ver
            ver=$("$candidate" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" 2>/dev/null || echo "0.0")
            local major=${ver%%.*}
            local minor=${ver#*.}
            if [[ "$major" -ge 3 && "$minor" -ge 10 ]]; then
                PYTHON="$candidate"
                ok "Python: $PYTHON ($ver)"
                return 0
            fi
        fi
    done
    err "Python 3.10+ not found. Install it first."
    exit 1
}

# ── Find hermes-agent ───────────────────────────────────────────────
find_hermes() {
    local candidates=(
        "${HERMES_AGENT_REPO:-}"
        "$HOME/.hermes/hermes-agent"
        "$HOME/.local/share/hermes/hermes-agent"
        "/usr/local/share/hermes/hermes-agent"
        "$DASHBOARD_DIR/../hermes-agent"
    )
    for p in "${candidates[@]}"; do
        [[ -z "$p" ]] && continue
        if [[ -d "$p/skills" ]]; then
            HERMES_REPO="$p"
            ok "hermes-agent: $HERMES_REPO"
            return 0
        fi
    done
    err "hermes-agent not found. Set HERMES_AGENT_REPO or install to ~/.hermes/hermes-agent"
    exit 1
}

# ── Find hermes-agent-self-evolution ────────────────────────────────
find_evolution() {
    local candidates=(
        "$HOME/.hermes/hermes-agent-self-evolution"
        "$DASHBOARD_DIR/../hermes-agent-self-evolution"
        "$HOME/dev/hermes-agent-self-evolution"
    )
    for p in "${candidates[@]}"; do
        if [[ -d "$p/evolution" ]]; then
            EVOLUTION_DIR="$p"
            ok "self-evolution: $EVOLUTION_DIR"
            return 0
        fi
    done
    warn "hermes-agent-self-evolution not found (evolution features will be limited)"
    EVOLUTION_DIR=""
}

# ── Setup Python venv ───────────────────────────────────────────────
setup_python_deps() {
    banner "Setting up Python backend"

    if [[ ! -d "$BACKEND_DIR/venv" ]]; then
        info "Creating venv..."
        "$PYTHON" -m venv "$BACKEND_DIR/venv"
    fi

    # Activate venv
    source "$BACKEND_DIR/venv/bin/activate"

    info "Installing Python deps..."
    pip install -q --upgrade pip
    pip install -q -r "$BACKEND_DIR/requirements.txt"

    # Also install evolution deps if available
    if [[ -n "$EVOLUTION_DIR" && -f "$EVOLUTION_DIR/pyproject.toml" ]]; then
        info "Installing evolution deps..."
        pip install -q dspy click rich pyyaml openai 2>/dev/null || warn "Some evolution deps failed (non-critical)"
    fi

    ok "Python deps installed"
}

# ── Setup Node deps ─────────────────────────────────────────────────
setup_node_deps() {
    banner "Setting up Node.js frontend"

    if ! command -v node &>/dev/null; then
        err "Node.js not found. Install from https://nodejs.org"
        exit 1
    fi

    local node_ver
    node_ver=$(node -v | tr -d 'v' | cut -d. -f1)
    if [[ "$node_ver" -lt 18 ]]; then
        err "Node.js 18+ required (found $(node -v))"
        exit 1
    fi
    ok "Node.js: $(node -v)"

    if [[ ! -d "$DASHBOARD_DIR/node_modules" ]]; then
        info "Installing npm deps..."
        cd "$DASHBOARD_DIR"
        npm install --silent
    fi
    ok "Node deps installed"
}

# ── Generate .env ───────────────────────────────────────────────────
generate_env() {
    banner "Generating configuration"

    local env_file="$DASHBOARD_DIR/.env.local"
    cat > "$env_file" << EOF
# Auto-generated by install.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
NEXT_PUBLIC_API_URL=http://localhost:8787
HERMES_AGENT_REPO=$HERMES_REPO
EVOLUTION_DIR=$EVOLUTION_DIR
PYTHON=$(which "$PYTHON" 2>/dev/null || echo "$PYTHON")
EOF
    ok "Config: $env_file"
}

# ── Create start script ─────────────────────────────────────────────
create_start_script() {
    local start_script="$DASHBOARD_DIR/start.sh"
    cat > "$start_script" << 'STARTEOF'
#!/usr/bin/env bash
# Hermes Dashboard — Start script
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"

# Load env
[[ -f "$DIR/.env.local" ]] && set -a && source "$DIR/.env.local" && set +a

echo "╔══════════════════════════════════════════╗"
echo "║  Hermes Evolution Dashboard              ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# Start backend
echo "▸ Starting backend (port 8787)..."
source "$DIR/backend/venv/bin/activate"
export HERMES_AGENT_REPO="${HERMES_AGENT_REPO:-$HOME/.hermes/hermes-agent}"
export PYTHONPATH="${EVOLUTION_DIR:-$HOME/.hermes/hermes-agent-self-evolution}"
uvicorn backend.main:app --host 0.0.0.0 --port 8787 &
BACKEND_PID=$!

# Wait for backend
for i in $(seq 1 15); do
    curl -sf http://localhost:8787/api/health >/dev/null 2>&1 && break
    sleep 0.5
done
echo "✓ Backend online (PID $BACKEND_PID)"

# Start frontend
echo "▸ Starting frontend (port 3001)..."
PORT=3001 npm run dev --prefix "$DIR" &
FRONTEND_PID=$!
echo "✓ Frontend starting..."
echo ""
echo "  Dashboard: http://localhost:3001"
echo "  API:       http://localhost:8787"
echo ""
echo "  Press Ctrl+C to stop"
echo ""

# Cleanup on exit
cleanup() {
    echo ""
    echo "Stopping..."
    kill $BACKEND_PID 2>/dev/null || true
    kill $FRONTEND_PID 2>/dev/null || true
    exit 0
}
trap cleanup INT TERM

wait
STARTEOF
    chmod +x "$start_script"
    ok "Start script: $start_script"
}

# ── Count skills (for verification) ─────────────────────────────────
count_skills() {
    if [[ -d "$HERMES_REPO/skills" ]]; then
        local md_count desc_count total
        md_count=$(find "$HERMES_REPO/skills" -name "SKILL.md" 2>/dev/null | wc -l | tr -d ' ')
        desc_count=$(find "$HERMES_REPO/skills" -name "DESCRIPTION.md" 2>/dev/null | wc -l | tr -d ' ')
        total=$((md_count + desc_count))
        ok "Skills found: $total ($md_count SKILL.md + $desc_count DESCRIPTION.md)"
    fi
}

# ═══════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════
banner "Hermes Dashboard Installer"

detect_os
find_python
find_hermes
find_evolution
count_skills
setup_python_deps
setup_node_deps
generate_env
create_start_script

banner "Installation complete!"
echo "  Start with:  ./start.sh"
echo "  Dashboard:   http://localhost:3001"
echo ""
