"""
⑥ DESPLIEGA — Skill Deployer Module

Auto-registers compiled and validated skills into the skill registry.
Creates SKILL.md files and makes them available to all agents.

This is the "birth" — the skill becomes real and accessible.
"""

from __future__ import annotations
import shutil
from datetime import datetime
from pathlib import Path
from typing import Optional

from .models import SkillGenesisPacket, CompilationResult, MetricSnapshot

SKILLS_DIR = Path.home() / ".hermes" / "skills"


class SkillDeployer:
    """Deploys validated skills to the multi-agent skill registry."""

    def __init__(self):
        SKILLS_DIR.mkdir(parents=True, exist_ok=True)
        self.deployment_log = Path.home() / ".hermes" / "traces" / "deployments.jsonl"

    # ── Deploy ──────────────────────────────────────────────────────
    def deploy(
        self,
        packet: SkillGenesisPacket,
        compilation: CompilationResult,
        validation: MetricSnapshot,
    ) -> dict:
        """Deploy a validated skill to the registry.

        Returns deployment info with paths and status.
        """
        if not validation.passed:
            return {
                "deployed": False,
                "skill_name": compilation.skill_name,
                "reason": f"Validation failed. Delta {validation.deltas} < threshold {packet.threshold}",
            }

        # Determine skill category
        category = self._categorize(packet)

        # Create skill directory
        skill_dir = SKILLS_DIR / category / compilation.skill_name
        skill_dir.mkdir(parents=True, exist_ok=True)

        # Generate SKILL.md
        skill_md = self._generate_skill_md(packet, compilation, validation)
        (skill_dir / "SKILL.md").write_text(skill_md)

        # Copy compiled artifacts if they exist
        compiled_path = Path(compilation.skill_path)
        if compiled_path.exists():
            for f in compiled_path.glob("*"):
                if f.name != "SKILL.md":
                    dest = skill_dir / f.name
                    if f.is_dir():
                        shutil.copytree(f, dest, dirs_exist_ok=True)
                    else:
                        shutil.copy2(f, dest)

        # Log deployment
        deploy_info = {
            "deployed": True,
            "skill_name": compilation.skill_name,
            "category": category,
            "skill_dir": str(skill_dir),
            "packet_id": packet.packet_id,
            "intent": packet.intent,
            "delta": validation.deltas,
            "threshold": packet.threshold,
            "passed": validation.passed,
            "deployed_at": datetime.now().isoformat(),
            "target_agent": packet.target_agent,
            "compilation_iteration": compilation.attempt,
            "dspy_score": compilation.best_score,
        }

        with open(self.deployment_log, "a") as f:
            f.write(__import__('json').dumps(deploy_info) + "\n")

        return deploy_info

    # ── SKILL.md Generation ─────────────────────────────────────────
    def _generate_skill_md(
        self,
        packet: SkillGenesisPacket,
        compilation: CompilationResult,
        validation: MetricSnapshot,
    ) -> str:
        """Generate a professional SKILL.md for the new skill."""
        return f"""---
name: {compilation.skill_name}
category: software-development
description: Auto-generated by Promethean Cycle. {packet.intent}
auto_generated: true
promethean_packet_id: {packet.packet_id}
generated_at: {datetime.now().isoformat()}
---

# {compilation.skill_name.replace('-', ' ').title()}

> 🤖 Auto-compiled by the Promethean Cycle (GEPA ⊕ DSPy)
> **Intent:** {packet.intent}
> **Delta:** {validation.deltas}
> **Threshold:** {packet.threshold} → {"✅ PASSED" if validation.passed else "❌ FAILED"}

## When to Use

This skill was automatically generated in response to detected operational failures.
Use when encountering errors matching the pattern:

```
{packet.error_signature if hasattr(packet, 'error_signature') else packet.intent[:100]}
```

## Validation Results

| Metric | Baseline | Evolved | Delta |
|--------|----------|---------|-------|
{chr(10).join(f"| {k} | {validation.baseline.get(k, 'N/A')} | {validation.evolved.get(k, 'N/A')} | {v} |" for k, v in validation.deltas.items())}

- **Dataset size:** {validation.dataset_size}
- **Holdout size:** {validation.holdout_size}
- **DSPy Best Score:** {compilation.best_score}
- **Compilation iterations:** {compilation.iterations}

## Target Agents

{packet.target_agent}

## Compilation Strategy

BetterTogether: `{packet.strategy}`

## Signature

```
{packet.signature}
```

## Notes

This skill was born from the Promethean Cycle — the dashboard detected a capability gap,
GEPA formulated a learning objective, DSPy compiled the solution, and the delta validator
confirmed its effectiveness. No human wrote this skill. The system learned it.
"""

    # ── Categorization ──────────────────────────────────────────────
    def _categorize(self, packet: SkillGenesisPacket) -> str:
        """Determine the best category for this skill."""
        intent_lower = packet.intent.lower()
        if any(kw in intent_lower for kw in ["deploy", "build", "docker", "ci", "pipeline"]):
            return "devops"
        elif any(kw in intent_lower for kw in ["database", "migration", "drizzle", "sql"]):
            return "backend-patterns"
        elif any(kw in intent_lower for kw in ["test", "validation", "qa", "verify"]):
            return "testing"
        elif any(kw in intent_lower for kw in ["auth", "login", "session", "oauth"]):
            return "security"
        elif any(kw in intent_lower for kw in ["expo", "react-native", "mobile", "app"]):
            return "software-development"
        else:
            return "software-development"

    # ── Registry Update ─────────────────────────────────────────────
    def get_deployment_history(self, limit: int = 20) -> list[dict]:
        """Get recent deployment history."""
        if not self.deployment_log.exists():
            return []

        deployments = []
        with open(self.deployment_log) as f:
            for line in f:
                if line.strip():
                    deployments.append(__import__('json').loads(line))

        return deployments[-limit:]


# ── Singleton ───────────────────────────────────────────────────────
_deployer: Optional[SkillDeployer] = None


def get_deployer() -> SkillDeployer:
    global _deployer
    if _deployer is None:
        _deployer = SkillDeployer()
    return _deployer
